apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-chatbot
  labels:
    app: deployment-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-chatbot
  template:
    metadata:
      labels:
        app: deployment-chatbot
    spec:
        containers:
        - image: davnm5/chatbot:latest
          name: chatbot
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
            hostPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  labels:
    app: deployment-chatbot
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30001
  selector:
    app: deployment-chatbot
    
  