apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-chatbot
  labels:
    app: deployment-chatbot
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-chatbot
  template:
    metadata:
      labels:
        app: deployment-chatbot
    spec:
        containers:
        - image: davnm5/chatbot:latest
          name: chatbot
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
        nodeSelector:
          beta.kubernetes.io/os: linux
          nodelabel: app
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  labels:
    app: deployment-chatbot
spec:
  type: LoadBalancer
  ports:
  - port: 30001
    targetPort: 5000
    protocol: TCP
  selector:
    app: deployment-chatbot
    
  